# -*- coding: utf-8 -*-
"""heart_disease_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11K2yUQFKRjREtIXZowAOS1ixqXBrp3Oq
"""

import streamlit as st
import numpy as np
import tensorflow as tf

# Load model
model = tf.keras.models.load_model('heart_ann_model.h5')

st.set_page_config(page_title="Heart Disease Prediction", layout="centered")
st.title("❤️ Heart Disease Risk Prediction Using ANN")
st.markdown("Enter the following details to check your risk of heart disease:")

# Input fields
age = st.number_input("Age", 1, 120)
sex = st.selectbox("Sex", options=["Male", "Female"])
cp = st.selectbox("Chest Pain Type (cp)", [0, 1, 2, 3])
trestbps = st.number_input("Resting Blood Pressure (trestbps)", 80, 200)
chol = st.number_input("Cholesterol (chol)", 100, 600)
fbs = st.selectbox("Fasting Blood Sugar > 120 mg/dl (fbs)", [0, 1])
restecg = st.selectbox("Resting ECG (restecg)", [0, 1, 2])
thalach = st.number_input("Maximum Heart Rate Achieved (thalach)", 60, 220)
exang = st.selectbox("Exercise Induced Angina (exang)", [0, 1])
oldpeak = st.number_input("Oldpeak (ST depression)", 0.0, 10.0, step=0.1)
slope = st.selectbox("Slope of the Peak Exercise ST segment", [0, 1, 2])
ca = st.selectbox("Number of Major Vessels Colored (ca)", [0, 1, 2, 3, 4])
thal = st.selectbox("Thalassemia (thal)", [0, 1, 2, 3])

# Convert categorical
sex = 1 if sex == "Male" else 0

# Predict
if st.button("🔍 Predict"):
    user_input = np.array([[age, sex, cp, trestbps, chol, fbs,
                            restecg, thalach, exang, oldpeak,
                            slope, ca, thal]])
    prediction = model.predict(user_input)

    result = "🚨 High Risk of Heart Disease" if prediction[0][0] > 0.5 else "✅ Low Risk of Heart Disease"
    st.subheader("Prediction Result:")
    st.success(result)